require('dotenv').config();
const express = require("express");
const app= express();
const bodyParser=require('body-parser');
const usersController = require('./server/routes/users');
const postsController = require('./server/routes/posts');
const { requireAuth } = require('./server/models/auth');
app.use(express.json());
app.use(express.static(__dirname + "/public"));
app.get('/', (req,res) => res.sendFile(path.join(__dirname, '/public', 'index.html')));
app.use(function(req, res, next){
    res.header("Access-Control-Allow-Origin","*");
    res.header("Access-Control-Allow-Headers","Origin,X-Request-Width,Content-Type,Authorization");
    res.header("Access-Control-Allow-Methods","GET,POST,PUT,DELETE,OPTIONS");
    next();
});
app.use(bodyParser.urlencoded({extended: true})); 
app.use(bodyParser.json()); 
app.use('/api/users', usersController);
app.use('/api/posts', postsController);
const SERVERPORT = process.env.PORT || 3000;
app.listen(SERVERPORT, ()=> console.log(`Server started on port ${SERVERPORT}`));
