require('dotenv').config();
const express = require("express");
const app= express();
const bodyParser=require('body-parser');
const cookieParser = require('cookie-parser');
const cors = require('cors');
const usersController = require('./server/routes/users');
const postsController = require('./server/routes/posts');

app.use(express.static(__dirname + "/public"));
app.get('/', (req,res) => res.sendFile(path.join(__dirname, '/public', 'index.html')));
app.use(cors({ credentials:true, origin:'https://kokkalan.herokuapp.com' }));
app.use(cookieParser());
app.use(express.json());
app.use(bodyParser.urlencoded({extended: true})); 
app.use(bodyParser.json()); 
app.use('/api/users', usersController);
app.use('/api/posts', postsController);
const SERVERPORT = process.env.PORT || 3000;
app.listen(SERVERPORT, ()=> console.log(`Server started on port ${SERVERPORT}`));
